# Generated by Django 3.1 on 2020-09-07 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_user_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='item_status',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='bid',
            name='list_item',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.auctionlisting'),
        ),
    ]
