# Generated by Django 3.1 on 2020-09-09 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200908_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='winning_price',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
