# Generated by Django 3.1 on 2020-09-09 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auctionlisting_winning_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='listing_comment',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_datetime',
            new_name='createddatetime',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='list_item',
        ),
        migrations.AddField(
            model_name='comment',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.auctionlisting'),
        ),
    ]
