# Generated by Django 3.1.1 on 2020-12-22 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_user_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='likereceiver',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='likegiver',
            new_name='user',
        ),
    ]
